# Generated by Django 4.2 on 2023-04-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
